apiVersion: v1
kind: Secret
metadata:
  name: healthconnect-secrets
  # The name we will use to reference this secret later
type: Opaque
# Opaque just means it's a standard key-value secret
stringData:
  # stringData allows us to write plain text here. 
  # When OpenShift saves it, it will automatically encrypt/encode it for us.
  GROQ_API_KEY: "replace_with_your_groq_key"
  SENDER_EMAIL: "replace_with_your_email"
  SENDER_PASSWORD: "replace_with_your_password"
  SERPER_API_KEY: "replace_with_your_serper_key"